name: Build
on: [push, pull_request]
jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: install dependencies
        run: npm install && npm install -g pnpm
      - name: build
        run: npm run build
      - name: pack
        run: npm run pack

  build_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: install dependencies
        run: npm install && npm install -g pnpm
      - name: build
        run: npm run build
      - name: pack
        run: npm run pack

  build_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: install dependencies
        run: npm install && npm install -g pnpm
      - name: build
        run: npm run build
      - name: pack
        run: npm run pack
